### ISSUE TITLE
barra de progresso não aparece sempre [BUG]

### ISSUE THREAD

**Issue by josaum** [jquant/jai-sdk#170]
**Describe the bug**
As vezes a barra de progresso de treinamento não aparece.

**To Reproduce**
j.setup -> db_type = SelfSupervised ; utilizando-se o mycelia_bases

![image](https://user-images.githubusercontent.com/8642345/113180772-805eac00-9227-11eb-8376-52327a0feba6.png)

**Comment by laurademenezes** [comment]
para db_type='FastText' não apareceu nenhuma vez para mim a barra de progresso de treinamento tanto no setup quanto no resolution.

**Comment by p-freire** [comment]
Possible scenarios:

1. Database is too small and thus the training part happens in a shorter period of time than `frequency_seconds`. Unlikely, but it's a possibility.
2. Throughput issue (on client or server side, or both). Depending on how busy a pod is, the `status` response time might degrade. Loosening the threholds for new pods may help improve performance (with a cost trade-off). On client side, network problems (unstable connection, slow connection, etc) can make `status` responses get sluggish as well.

Closing this issue since both scenarios are not directly related to the SDK per se. Feel free, however, to reopen it if this behavior gets recurrent.
